sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t ansible_lint:alpine3 ./alpine3/ -f ./alpine3/Dockerfile
      - docker image ls
      - docker tag ansible_lint:alpine3 $DOCKER_USERNAME/ansible_lint:alpine3
      - docker push $DOCKER_USERNAME/ansible_lint:alpine3
      - docker build -t ansible_lint:centos7 ./CentOS7/ -f ./CentOS7/Dockerfile
      - docker image ls
      - docker tag ansible_lint:centos7 $DOCKER_USERNAME/ansible_lint:centos7
      - docker push $DOCKER_USERNAME/ansible_lint:centos7
      - docker build -t ansible_lint:debian9 ./Debian9/ -f ./Debian9/Dockerfile
      - docker image ls
      - docker tag ansible_lint:debian9 $DOCKER_USERNAME/ansible_lint:debian9
      - docker push $DOCKER_USERNAME/ansible_lint:debian9
      - docker build -t ansible_lint:ubuntu16 ./Ubuntu16.04/ -f ./Ubuntu16.04/Dockerfile
      - docker image ls
      - docker tag ansible_lint:ubuntu16 $DOCKER_USERNAME/ansible_lint:ubuntu16
      - docker push $DOCKER_USERNAME/ansible_lint:ubuntu16
